apiVersion: apps/v1
kind: Deployment
metadata:
  name: project 
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project 
  template:
    metadata:
      labels:
        app: project 
    spec:
      serviceAccountName: terminal-sa 
      imagePullSecrets:
      - name: project-secret
      containers:
      - name: project 
        image: mazen0202/mazen-devops-portfolio:9469fe805dd52c9cddfb9f251cda25b72d86d65d
        ports:
        - containerPort: 3000