apiVersion: apps/v1
kind: Deployment
metadata:
  name: project 
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project 
  template:
    metadata:
      labels:
        app: project 
    spec:
      serviceAccountName: terminal-sa 
      imagePullSecrets:
      - name: project-secret
      containers:
      - name: project 
        image: ghcr.io/maze0207-byte/mazen-devops-portfolio:latest
        ports:
        - containerPort: 3000