apiVersion: apps/v1
kind: Deployment
metadata:
  name: project 
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project 
  template:
    metadata:
      labels:
        app: project 
    spec:
      serviceAccountName: terminal-sa 
      containers:
      - name: project 
        image: mazen2025/mazen-devops-portfolio:79cd5565bd62a5c78f43f221329927a614c65f6c
        ports:
        - containerPort: 3000